# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gui_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet project dependencies
        run: cd IMDB && dotnet restore
      - name: Restore Playwright Project
        run: cd E2ETesting-main && dotnet restore
      - name: Ensure browsers are installed
        run: cd E2ETesting-main && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps # byt ut ShopTester.Tests mot ditt test projekt sökväg
      - name: Build Playwright Project
        run: cd E2ETesting-main && dotnet build
      - name: Start server
        run: cd IMDB # && nohup dotnet run
      - name: Run GUI-tests
        run: cd E2ETesting-main && dotnet test
